services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./docker/backend/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/backend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/backend/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
      target: dev
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql-db # ←追加
    environment:
      MYSQL_DATABASE: react-portfolio
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./docker/backend/mysql/myconf:/etc/mysql/conf.d
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

# ネットワーク設定を追加
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  frontend_node_modules:
